name: Access ID Workflow

on:
  push:
    branches:
      - '**'  # Runs on any branch push

jobs:
  test-job:
    runs-on: ubuntu-latest  # ✅ Ensuring the correct runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print ACCESS_ID
        run: echo "The ACCESS_ID is ${{ vars.ACCESS_ID }}"
