name: PostgreSQL Service Test

on: [push, pull_request]

jobs:
  test-postgres-service:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U testuser"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          until nc -z localhost 5432; do
            echo "PostgreSQL is not ready yet. Retrying in 1s..."
            sleep 1
          done
          echo "PostgreSQL is up and running!"

      - name: Verify PostgreSQL Service
        run: |
          PGPASSWORD=testpassword psql -h localhost -U testuser -d testdb -c "SELECT version();"
