name: GitHub Secret Test

on:
  push:
    branches:
      - "**"  # Runs on every push

jobs:
  test_secret:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: Use GitHub Secret Securely
        env:
          SECRET_VALUE: ${{ secrets.SECRET }}
        run: |
          echo "The secret is ${{ secrets.SECRET }}"
